-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 20:14:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema integradoranorma5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `integradoranorma5` ;

-- -----------------------------------------------------
-- Schema integradoranorma5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integradoranorma5` DEFAULT CHARACTER SET utf8 ;
USE `integradoranorma5` ;

-- -----------------------------------------------------
-- Table `integradoranorma5`.`cat_country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cat_country` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cat_country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `country_UNIQUE` (`country` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`address` ;

CREATE TABLE IF NOT EXISTS `address` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_country` int NOT NULL,
  `state` varchar(100) NOT NULL,
  `locality` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `main_street` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `street1` varchar(100) DEFAULT NULL,
  `street2` varchar(100) DEFAULT NULL,
  `references` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `address-cat_country` (`id_country`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb3;



-- -----------------------------------------------------
-- Table `integradoranorma5`.`cat_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cat_brand` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cat_brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `id_address` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `cat_brand-address` (`id_address` ASC) VISIBLE,
  CONSTRAINT `cat_brand-address`
    FOREIGN KEY (`id_address`)
    REFERENCES `integradoranorma5`.`address` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`cat_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cat_category` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cat_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_UNIQUE` (`category` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`product` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_category` INT NOT NULL,
  `id_brand` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(120) CHARACTER SET 'utf8mb3' NOT NULL,
  `description` LONGTEXT NOT NULL,
  `specifications` LONGTEXT NOT NULL,
  `dimensions` LONGTEXT NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `discount` DOUBLE NULL DEFAULT '0',
  `status` INT NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `product-cat_category` (`id_category` ASC) VISIBLE,
  INDEX `product-cat_brand` (`id_brand` ASC) VISIBLE,
  CONSTRAINT `product-cat_brand`
    FOREIGN KEY (`id_brand`)
    REFERENCES `integradoranorma5`.`cat_brand` (`id`),
  CONSTRAINT `product-cat_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `integradoranorma5`.`cat_category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`cat_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cat_user` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cat_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_of_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `type_of_user_UNIQUE` (`type_of_user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`user` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastnameF` VARCHAR(45) NOT NULL,
  `lastnameM` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_address` INT NOT NULL DEFAULT '1',
  `id_user` INT NOT NULL DEFAULT '3',
  `status` INT NOT NULL DEFAULT '1',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `user-cat_user` (`id_user` ASC) VISIBLE,
  INDEX `user-address` (`id_address` ASC) VISIBLE,
  CONSTRAINT `user-address`
    FOREIGN KEY (`id_address`)
    REFERENCES `integradoranorma5`.`address` (`id`),
  CONSTRAINT `user-cat_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `integradoranorma5`.`cat_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cart` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cart` (
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NULL DEFAULT '1',
  `last_update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `cart-user` (`id_user` ASC) VISIBLE,
  INDEX `cart-product` (`id_product` ASC) VISIBLE,
  CONSTRAINT `cart-product`
    FOREIGN KEY (`id_product`)
    REFERENCES `integradoranorma5`.`product` (`id`),
  CONSTRAINT `cart-user`
    FOREIGN KEY (`id_user`)
    REFERENCES `integradoranorma5`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`cat_history_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cat_history_process` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cat_history_process` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `icon_process` LONGTEXT NOT NULL,
  `name_process` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `process_name_UNIQUE` (`name_process` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`cat_payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cat_payment_method` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cat_payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen` LONGTEXT NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `payment_method_UNIQUE` (`payment_method` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`cat_payment_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`cat_payment_status` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`cat_payment_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `payment_status_UNIQUE` (`payment_status` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`history_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`history_process` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`history_process` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_process` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `history_process-cat_history_process_idx` (`id_process` ASC) VISIBLE,
  CONSTRAINT `history_process-cat_history_process`
    FOREIGN KEY (`id_process`)
    REFERENCES `integradoranorma5`.`cat_history_process` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`payment` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_method` INT NOT NULL,
  `id_status` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `payment-payment_method` (`id_method` ASC) VISIBLE,
  INDEX `payment-payment_status` (`id_status` ASC) VISIBLE,
  CONSTRAINT `payment-payment_method`
    FOREIGN KEY (`id_method`)
    REFERENCES `integradoranorma5`.`cat_payment_method` (`id`),
  CONSTRAINT `payment-payment_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `integradoranorma5`.`cat_payment_status` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `integradoranorma5`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integradoranorma5`.`sale` ;

CREATE TABLE IF NOT EXISTS `integradoranorma5`.`sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  `id_payment` INT NOT NULL,
  `id_process` INT NOT NULL DEFAULT '1',
  `total` DOUBLE NOT NULL,
  `quantity` INT NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `sale-payment` (`id_payment` ASC) VISIBLE,
  INDEX `sale-user` (`id_user` ASC) VISIBLE,
  INDEX `sale-product` (`id_product` ASC) VISIBLE,
  INDEX `sale-history_process_idx` (`id_process` ASC) VISIBLE,
  CONSTRAINT `sale-history_process`
    FOREIGN KEY (`id_process`)
    REFERENCES `integradoranorma5`.`history_process` (`id`),
  CONSTRAINT `sale-payment`
    FOREIGN KEY (`id_payment`)
    REFERENCES `integradoranorma5`.`payment` (`id`),
  CONSTRAINT `sale-product`
    FOREIGN KEY (`id_product`)
    REFERENCES `integradoranorma5`.`product` (`id`),
  CONSTRAINT `sale-user`
    FOREIGN KEY (`id_user`)
    REFERENCES `integradoranorma5`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
